/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fed488",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c6c6c9",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#848484",
        "inverse-on-surface": "#f0f1f2",
        "on-surface-variant": "#44474a",
        outline: "#75777a",
        primary: "#000101",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "surface-container": "#edeeef",
        "muted-bronze": "#8E7341",
        "on-tertiary-fixed-variant": "#464747",
        "secondary-fixed": "#ffdea5",
        "success-emerald": "#2D6A4F",
        background: "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "on-secondary-container": "#785a1a",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#5d5e61",
        "on-surface": "#191c1d",
        "on-primary": "#ffffff",
        "primary-container": "#1a1c1e",
        "inverse-surface": "#2e3132",
        "surface-border": "#E2E8F0",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "surface-container-lowest": "#ffffff",
        "artisan-gold": "#C5A059",
        secondary: "#775a19",
        "inverse-primary": "#c6c6c9",
        "on-primary-fixed": "#1a1c1e",
        "tertiary-fixed": "#e3e2e2",
        "on-tertiary-fixed": "#1b1c1c",
        "warning-amber": "#B07D05",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c6ca",
        "deep-charcoal": "#1A1C1E",
        "secondary-fixed-dim": "#e9c176",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#5d4201",
        "primary-fixed": "#e2e2e5",
        surface: "#f8f9fa",
        tertiary: "#000101",
        "on-primary-container": "#838486",
        "on-secondary-fixed": "#261900",
        "on-primary-fixed-variant": "#454749",
        "tertiary-fixed-dim": "#c7c6c6",
        "error-container": "#ffdad6",
      },
      // NOTE: the Stitch export's embedded Tailwind config sets `full: "0.75rem"`,
      // which renders circular avatars/icon-badges as rounded squares. Fixed to a
      // true pill/circle radius here — see DESIGN.md "Inconsistencies flagged" #1.
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "max-content-width": "1440px",
        gutter: "24px",
        xl: "32px",
        sm: "8px",
        lg: "24px",
        md: "16px",
        xs: "4px",
        base: "4px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "code-label": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "code-label": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
